user:
  gravatar_size: 80
  email:
    max_length: 255
  password:
    min_length: 6
    max_length: 128
  is_blocked: "1"
  is_unblocked: "0"
  max_image_size_num: 3
  max_image_size: <%= 3.megabytes %>
  phone_regex: !ruby/regexp /(03|09|01[2|6|8|9])+([0-9]{8})\b/
  default_password: "123123"
session:
  remember_me?: "1"
campaign:
  title_max_length: 255
  min_total_amount: 0
  max_image_size_num: 5
  max_image_size: <%= 5.megabytes %>
  format_image_accept: <%= %w(image/jpeg image/gif image/png) %>
  per_page: 8
  page_show_homepage: 1
  success_show_homepage: 3
  share_fb_prefix: "https://www.facebook.com/sharer/sharer.php?u="
  max_tags_size: 3
  min_faker_amount: 10000
  max_faker_amount: 500000
donation:
  min_amount: 0
  max_message_length: 255
  per_page: 5
  default_amount: 10000
  min_faker_amount: 10000
  max_faker_amount: 90000
comment:
  max_content_length: 500
  per_page: 5
tag:
  max_length: 50
currency:
  min: 0
  step: 1000
